title: arhouse.tv 
description: New Entertainment
baseurl: ""
url: "https://arhouse.tv" 
theme: minima
plugins:
  - jekyll-feed

# -------- ^ Default ^ ------------

sass:
    sass_dir: _sass\
    style: compressed
include: ['_pages']
